[2024-02-13T12:13:46.927+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: baserowdata.consumer_task scheduled__2024-02-12T05:20:00+00:00 [queued]>
[2024-02-13T12:13:46.953+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: baserowdata.consumer_task scheduled__2024-02-12T05:20:00+00:00 [queued]>
[2024-02-13T12:13:46.954+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-13T12:13:47.026+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): consumer_task> on 2024-02-12 05:20:00+00:00
[2024-02-13T12:13:47.044+0000] {standard_task_runner.py:60} INFO - Started process 196 to run task
[2024-02-13T12:13:47.061+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'baserowdata', 'consumer_task', 'scheduled__2024-02-12T05:20:00+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/consumer_dag.py', '--cfg-path', '/tmp/tmpzasp9idu']
[2024-02-13T12:13:47.073+0000] {standard_task_runner.py:88} INFO - Job 41: Subtask consumer_task
[2024-02-13T12:13:47.176+0000] {task_command.py:423} INFO - Running <TaskInstance: baserowdata.consumer_task scheduled__2024-02-12T05:20:00+00:00 [running]> on host b9c9154d9bc2
[2024-02-13T12:13:47.363+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='baserowdata' AIRFLOW_CTX_TASK_ID='consumer_task' AIRFLOW_CTX_EXECUTION_DATE='2024-02-12T05:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-12T05:20:00+00:00'
[2024-02-13T12:13:47.934+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:13:49.161+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:13:50.481+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:13:51.741+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:13:52.499+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:13:53.101+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:13:53.690+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:13:54.276+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:13:54.848+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:13:55.496+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:13:56.053+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:13:56.706+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:13:57.514+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:13:58.202+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:13:58.896+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:14:00.175+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:14:00.799+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:14:01.420+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:14:02.114+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:14:02.922+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:14:03.852+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:14:04.499+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:14:05.323+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:14:06.124+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:14:06.830+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:14:08.695+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:14:09.963+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:14:10.839+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:14:11.564+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:14:12.322+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:14:13.003+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:14:13.349+0000] {logging_mixin.py:188} INFO - İstek başarısız. HTTP yanıt kodu: 429
[2024-02-13T12:14:13.350+0000] {logging_mixin.py:188} INFO - {"detail":"Request was throttled. Expected available in 29 seconds."}
[2024-02-13T12:14:14.010+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:14:14.655+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:14:15.233+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:14:15.953+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:14:16.649+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:14:17.177+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:14:17.872+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:14:18.485+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:14:19.003+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:14:19.556+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:14:20.141+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:14:20.663+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:14:21.162+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:14:21.692+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:14:22.216+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:14:22.726+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:14:23.322+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:14:23.998+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:14:24.721+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:14:25.517+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:14:26.189+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:14:26.694+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:14:27.344+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:14:28.116+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:14:28.422+0000] {logging_mixin.py:188} INFO - İstek başarısız. HTTP yanıt kodu: 429
[2024-02-13T12:14:28.423+0000] {logging_mixin.py:188} INFO - {"detail":"Request was throttled. Expected available in 29 seconds."}
[2024-02-13T12:14:28.980+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:14:29.963+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:14:30.480+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:14:31.095+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:14:31.672+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:14:32.189+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:14:32.734+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:14:33.255+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to None. Terminating instance.
[2024-02-13T12:14:33.258+0000] {process_utils.py:131} INFO - Sending 15 to group 196. PIDs of all processes in the group: [196]
[2024-02-13T12:14:33.258+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 196
[2024-02-13T12:14:33.259+0000] {taskinstance.py:2450} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-02-13T12:14:33.272+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/consumer_dag.py", line 57, in main
    add_row_to_baserow(record, token)
  File "/opt/airflow/dags/consumer_dag.py", line 16, in add_row_to_baserow
    response = requests.post(
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/airflow/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 462, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/usr/local/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.8/ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.8/ssl.py", line 1132, in read
    return self._sslobj.read(len, buffer)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2452, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-02-13T12:14:33.280+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=baserowdata, task_id=consumer_task, execution_date=20240212T052000, start_date=20240213T121346, end_date=20240213T121433
[2024-02-13T12:14:33.304+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 41 for task consumer_task ((psycopg2.errors.ForeignKeyViolation) insert or update on table "task_fail" violates foreign key constraint "task_fail_ti_fkey"
DETAIL:  Key (dag_id, task_id, run_id, map_index)=(baserowdata, consumer_task, scheduled__2024-02-12T05:20:00+00:00, -1) is not present in table "task_instance".

[SQL: INSERT INTO task_fail (task_id, dag_id, run_id, map_index, start_date, end_date, duration) VALUES (%(task_id)s, %(dag_id)s, %(run_id)s, %(map_index)s, %(start_date)s, %(end_date)s, %(duration)s) RETURNING task_fail.id]
[parameters: {'task_id': 'consumer_task', 'dag_id': 'baserowdata', 'run_id': 'scheduled__2024-02-12T05:20:00+00:00', 'map_index': -1, 'start_date': datetime.datetime(2024, 2, 13, 12, 13, 46, 928941, tzinfo=Timezone('UTC')), 'end_date': datetime.datetime(2024, 2, 13, 12, 14, 33, 280113, tzinfo=Timezone('UTC')), 'duration': 46}]
(Background on this error at: https://sqlalche.me/e/14/gkpj); 196)
[2024-02-13T12:14:33.351+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=196, status='terminated', exitcode=1, started='12:13:46') (196) terminated with exit code 1
[2024-02-13T12:17:26.227+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: baserowdata.consumer_task scheduled__2024-02-12T05:20:00+00:00 [queued]>
[2024-02-13T12:17:26.276+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: baserowdata.consumer_task scheduled__2024-02-12T05:20:00+00:00 [queued]>
[2024-02-13T12:17:26.276+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-13T12:17:26.318+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): consumer_task> on 2024-02-12 05:20:00+00:00
[2024-02-13T12:17:26.341+0000] {standard_task_runner.py:60} INFO - Started process 279 to run task
[2024-02-13T12:17:26.367+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'baserowdata', 'consumer_task', 'scheduled__2024-02-12T05:20:00+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/baserow.py', '--cfg-path', '/tmp/tmpgxzl5emz']
[2024-02-13T12:17:26.388+0000] {standard_task_runner.py:88} INFO - Job 52: Subtask consumer_task
[2024-02-13T12:17:26.767+0000] {task_command.py:423} INFO - Running <TaskInstance: baserowdata.consumer_task scheduled__2024-02-12T05:20:00+00:00 [running]> on host b9c9154d9bc2
[2024-02-13T12:17:27.338+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='baserowdata' AIRFLOW_CTX_TASK_ID='consumer_task' AIRFLOW_CTX_EXECUTION_DATE='2024-02-12T05:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-12T05:20:00+00:00'
[2024-02-13T12:17:28.372+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:17:28.941+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:17:30.189+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:17:31.564+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:17:32.450+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:17:38.363+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:17:39.313+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:17:40.325+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:17:40.848+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:17:41.513+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:17:45.040+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:17:45.710+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:17:46.252+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:17:46.793+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:17:47.425+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:17:48.029+0000] {logging_mixin.py:188} INFO - İstek başarılı.
[2024-02-13T12:17:48.040+0000] {logging_mixin.py:188} INFO - CSV dosyasında veri bulunmuyor. 10 dakika sonra tekrar kontrol edilecek.
[2024-02-13T12:17:48.055+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/baserow.py", line 45, in main
    "Rank": rows[0]["Rank"],
KeyError: 'Rank'
[2024-02-13T12:17:48.448+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=baserowdata, task_id=consumer_task, execution_date=20240212T052000, start_date=20240213T121726, end_date=20240213T121748
[2024-02-13T12:17:48.558+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 52 for task consumer_task ('Rank'; 279)
[2024-02-13T12:17:48.622+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-13T12:17:48.683+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
